runtime: python37

handlers:
  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: front-end/co2-gatech/index.html
    upload: front-end/co2-gatech/index.html
  - url: /index.css
    secure: always
    redirect_http_response_code: 301
    static_files: front-end/co2-gatech/index.css
    upload: front-end/co2-gatech/index.css
  - url: /index.js
    secure: always
    redirect_http_response_code: 301
    static_files: front-end/co2-gatech/index.js
    upload: front-end/co2-gatech/index.js
  - url: /gt-logo.png
    secure: always
    redirect_http_response_code: 301
    static_files: front-end/co2-gatech/gt-logo.png
    upload: front-end/co2-gatech/gt-logo.png
